### ISSUE TITLE
gcc + linux generate Colormap redefinition error

### ISSUE THREAD

**Issue by kmilo9999** [Twinklebear/imgui-transfer-function#2]
I dont know if you continue developing this lib, but I still use it and hopefully you can give some support.

Compiling with gcc 8.3 on  Linux , I get the following error:

./libs/UIHelpers/transfer_function_widget.h:35:8: error: using typedef-name Colormap after struct
 struct Colormap {
        ^~~~~~~~
In file included from /usr/include/X11/Xlib.h:44,
                 from install_Linux/include/GL/glxew.h:98,
                 from ../include/vrapp/VolumeVisualizationApp.h:8,
                 from /users/cdiaz8/data/cdiaz8/VR-Volumeviewer/src/vrapp/VolumeVisualizationApp.cpp:2:
/usr/include/X11/X.h:104:13: note: Colormap has a previous declaration here
 typedef XID Colormap;
             ^~~~~~~~

**Comment by Twinklebear** [comment]
Hi @kmilo9999 , thanks for opening this issue. It looks like my Colormap struct is colliding with a struct or typedef in your app, which is also named Colormap. I can fix this by adding a namespace to the library, which I should have done originally. I'll do that and close this issue after

**Comment by kmilo9999** [comment]
@Twinklebear 
Actually, It is colliding with a definition in the X11 library:

    /usr/include/X11/X.h:104:13: note: Colormap has a previous declaration here

**Comment by Twinklebear** [comment]
👍  

The library's now under the tfnw namespace, which should resolve the conflict.
