### ISSUE TITLE
Update Imgui implementation

### ISSUE THREAD

**Issue by kmilo9999** [Twinklebear/imgui-transfer-function#3]
Hi.

Have you tested the current transfer function widget implementation against newer versions of imgui ? ( they are on 1.87 and your tests link against 1.63)
I have an old version of this library, and I would like to update it with your latest changes.

**Comment by Twinklebear** [comment]
Hi @kmilo9999 , I haven't tested this repo against the latest version of ImGui but it should be compatible with it. Let me check it briefly now with the example app, there might just be some names that need to be updated

**Comment by Twinklebear** [comment]
I've just tested on ImGui 1.87 and everything looks to be working well! So I think you should be safe to update it
